// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqc-m96BMSbDkNPyOTvebpTUH8PV3XUo8',
    appId: '1:445409976748:web:692eae1532d78d81c25a09',
    messagingSenderId: '445409976748',
    projectId: 'fruits-460b8',
    authDomain: 'fruits-460b8.firebaseapp.com',
    storageBucket: 'fruits-460b8.firebasestorage.app',
    measurementId: 'G-CXHQ5ZSXFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1RQyuFdWb_PGKpvN3awGJHrsDHheAgm0',
    appId: '1:445409976748:android:ce8bc4f2502abebbc25a09',
    messagingSenderId: '445409976748',
    projectId: 'fruits-460b8',
    storageBucket: 'fruits-460b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBborFUA0Ug_T8XFXgWUG0h6kpNzl-CPtw',
    appId: '1:445409976748:ios:6e07b6cec15c13e4c25a09',
    messagingSenderId: '445409976748',
    projectId: 'fruits-460b8',
    storageBucket: 'fruits-460b8.firebasestorage.app',
    androidClientId: '445409976748-ea4rb1rjnsvs9rqolm0ojt0lliq4svi5.apps.googleusercontent.com',
    iosClientId: '445409976748-g95r6m95jiuif353d0ugfrkip4h1lc2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashbord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBborFUA0Ug_T8XFXgWUG0h6kpNzl-CPtw',
    appId: '1:445409976748:ios:6e07b6cec15c13e4c25a09',
    messagingSenderId: '445409976748',
    projectId: 'fruits-460b8',
    storageBucket: 'fruits-460b8.firebasestorage.app',
    androidClientId: '445409976748-ea4rb1rjnsvs9rqolm0ojt0lliq4svi5.apps.googleusercontent.com',
    iosClientId: '445409976748-g95r6m95jiuif353d0ugfrkip4h1lc2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashbord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqc-m96BMSbDkNPyOTvebpTUH8PV3XUo8',
    appId: '1:445409976748:web:c6082846d6666455c25a09',
    messagingSenderId: '445409976748',
    projectId: 'fruits-460b8',
    authDomain: 'fruits-460b8.firebaseapp.com',
    storageBucket: 'fruits-460b8.firebasestorage.app',
    measurementId: 'G-8FTTHH2ZXG',
  );
}
